### ISSUE TITLE
Mov and other file formats not returning exif data

### ISSUE THREAD

**Issue by jleatham** [tfeldmann/organize#313]
**Describe the bug**
Various file formats consistently do not report exif data, even though it exists.  I need exif data as createdate field always updates to time of upload to NAS, not date taken.

**Screenshots**
```
  - name: "Organize movies"
    locations:
      - /Volumes/.../
    filters:
      - extension: 
         - mov
      - exif
    actions:
      - echo: "{exif}"
```

Returns nothing, however, when I run exiftool on the various mov files, I see:
```
➜  ~ exiftool -time:all /Volumes/.../IMG_0015.MOV
File Modification Date/Time     : 2023:05:23 08:26:19-05:00
File Access Date/Time           : 2023:09:26 11:28:01-05:00
File Inode Change Date/Time     : 2023:05:23 08:26:19-05:00
Create Date                     : 2023:05:23 13:26:20
Modify Date                     : 2023:05:23 13:26:21
Track Create Date               : 2023:05:23 13:26:20
Track Modify Date               : 2023:05:23 13:26:21
Media Create Date               : 2023:05:23 13:26:20
Media Modify Date               : 2023:05:23 13:26:21
Creation Date                   : 2023:05:23 14:26:19+01:00
```
I've run exif filter on HEIC files without issue.

**Environment (please complete the following information):**

- OS: OSX Ventura 13.5.2
- Output of `organize --version`: organize, version 2.4.2

How can I go about troubleshooting this issue?

**Comment by tfeldmann** [comment]
Hi, thanks for reporting! Qt and MOV files are currently not supported by the `exifread` library we use. It's planned to be able to use [exiftool](https://exiftool.org) for exif extraction if available. This is currently on the backlog for me, but PRs are always welcome!

**Comment by tfeldmann** [comment]
I just released v3 with `exiftool` support. You need to set an environment variable `ORGANIZE_EXIFTOOL_PATH="exiftool"` and then organize uses exiftool under the hood.

**Comment by jleatham** [comment]
Apologies, but I am still having issues with this.  See above.
I provided the env variable:
```
> printenv
...
ORGANIZE_EXIFTOOL_PATH=exiftool
```

I verified that exiftool is being used for jpg if i add the extension to the filter:
```
2017-Feb-01-file.JPG
    - (echo) {'sourcefile': '/Volumes/...path.JPG', 'exiftool': {'exiftoolversion': 
12.52}, 'file': {'filename': '/Volumes/...path.JPG', 'directory': '/Volumes/...path', 'filesize': '2.0 
MB', 'resourceforksize': '659 bytes', 'filemodifydate': datetime.datetime(2017, 2, 1, 13, 31, 22)...
...
}}
```

However, it is not reading .MOV or .mp4 files.  I've verified that exiftool can read them (see above).

```
organize --version
organize v3.0.0
```

Any tips for troubleshooting?

**Comment by jleatham** [comment]
OK, i was troubleshooting the code and I see an issue:
in organize/filters/exif.py , you have a snippet:
```
line 158
    if "EXIF" not in data.keys():
        return dict()
```
So if EXIF key isn't found, send an empty { } .  

The jpg files have the EXIF key, but the .mov and .mp4 only have:
SourceFile
File
QuickTime
Composite

With the majority of the exif data under QuickTime, such as:
MajorBrand
CreateDate
Duration
ImageHeight
Megapixels
... other exif fields

When I commented the if statement out, the SIM succeeds and I get the echo of the exif data.
I haven't tried to do anything with it yet, and this is my first time looking at the code so would need to dig in more to see how we could fix this.

Hope this helps.

## Notes:
jpg keys:
```
{'SourceFile': 'path.JPG', 'ExifTool': {}, 'File': {}, 'EXIF': {}, 'MakerNotes': {}, 'Composite': {}}
```
mov and mp4 keys:
```
{'SourceFile':'path.MOV', 'ExifTool': {}, 'File': {}, 'QuickTime': {}, 'Composite': {}}
```

**Comment by tfeldmann** [comment]
Thanks a lot for reporting and debugging!
You have found the issue, the `EXIF` key is not always present for all file formats. Checking for `Composite` should work, though. This is now fixed in 0b185084cfdb406b708fb17ec304d0510718c406 and available in the next release.

**Comment by jleatham** [comment]
Glad to help, however!
Composite doesn't have create date and other important Exif data.  Examples:
```
'composite': {'imagesize': '1920x1080', 'megapixels': 2.1,
'avgbitrate': '3.26 Mbps', 'rotation': 0}

'composite': {'imagesize': '1920x1080', 'megapixels': 2.1,
'avgbitrate': '7.9 Mbps', 'gpsaltitude': '180.165 m', 'gpsaltituderef': 'Above
Sea Level', 'gpslatitude': '...', 'gpslongitude': '..." W', 'rotation': 90, 'gpsposition': '...'}

```

All the Exif data I need is in the `QuickTime` field

**Comment by tfeldmann** [comment]
The `Composite` key is only used to check whether the file includes any usable Exif data at all. This is because exiftool generates *some* data for all the formats. Otherwise the `exif`-filter would match all files, even simple PDFs and textfiles.

**Comment by jleatham** [comment]
oh, gotcha.  Makes sense.  But wouldn't the rules need to use the output?  If the keys and output are different each time based on manufacture, then the filters such as 
```
       - exif:
           exif.datetimeoriginal

or

- move: 
           dest: "/organized/{exif.exif.datetimeoriginal.year}-{name}.{extension}"
```
would not point to the right exif field.  Each rule would have to be experimented. 

I wonder if we could use exiftool flags such as `-time:all` , and others to grab the exact exif data from each file and build your data variable?  That way we are utilizing exiftools strength and the output would be consistent for all filetypes.

**Comment by tfeldmann** [comment]
I have to look into the -time:all flag, that might come really handy.

If you want to make sure your image contains the `exif` and `quicktime` data, you can filter like this:

```yaml
rules:
  - locations: .
    subfolders: true
    filters:
      - exif:
          exif:
          gps:
    actions:
      - echo: "Hello, World! {exif.gps} {exif.exif}"
```

The documentation is really lacking here.
